language: go
go:
- 1.0
- 1.1
- 1.2
- 1.3
- tip
before_install: 
- export TRAVIS_GO_VERSION_INT=`echo $TRAVIS_GO_VERSION | sed 's/[^0-9]//g'`
install: 
- if [[ $TRAVIS_GO_VERSION_INT -gt 111 ]]; then make packages; fi
script: 
- make packages
- if [[ $TRAVIS_GO_VERSION_INT -gt 111 ]]; then go test -v -covermode=count -coverprofile=./coverage.out && $HOME/gopath/bin/goveralls -coverprofile=./coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; else go test -v; fi 
env:
  global:
    secure: cuf/JbYhzVyqbRJQMJGuviz7IB/yT62ysAGynDaqB2FNWHZqXEJI6deSmRL2qhohyAmI3YPbgdZRAjukW0b85Vj1MOXHksOYBG9hzJJC6Z3k5gBRcXYVRv8W2+gjvimrd+40Cxev8T3WLjG0FB/khjHMb90x0HBS7IurwrpfsYo=
